// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbsdqclyiymbeszaplhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ic2RxY2x5aXltYmVzemFwbGhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzA1MTYsImV4cCI6MjA2OTAwNjUxNn0.c2xiKVgchdAmWk31NzxklXr8I87c-TU1_UK-LJkfuYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});